[build]
  publish = "dist"
  command = "node scripts/optimize-for-production-simple.js"

# Disable Next.js plugin completely
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Production context
[context.production]
  command = "node scripts/optimize-for-production-simple.js"